[package]
name = "osc_dispatcher"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.27.0", features = ["full"] }
rosc={ git = "https://github.com/MikHulk/rosc.git" }
rand="0.8.4"
